// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package reversingunorderedlist.proxies;

/**
 * 
 * 
 */
public class Orderline
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderlineMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ReversingUnorderedList.Orderline";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Date("Date"),
		TotalPrice("TotalPrice"),
		OrderlineStatus("OrderlineStatus"),
		Attribute5("Attribute5"),
		Attribute6("Attribute6"),
		Attribute7("Attribute7"),
		Attribute8("Attribute8"),
		Attribute9("Attribute9"),
		Orderline_Order("ReversingUnorderedList.Orderline_Order");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Orderline(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ReversingUnorderedList.Orderline"));
	}

	protected Orderline(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderlineMendixObject)
	{
		if (orderlineMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ReversingUnorderedList.Orderline", orderlineMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ReversingUnorderedList.Orderline");

		this.orderlineMendixObject = orderlineMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Orderline.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static reversingunorderedlist.proxies.Orderline initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return reversingunorderedlist.proxies.Orderline.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static reversingunorderedlist.proxies.Orderline initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new reversingunorderedlist.proxies.Orderline(context, mendixObject);
	}

	public static reversingunorderedlist.proxies.Orderline load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return reversingunorderedlist.proxies.Orderline.initialize(context, mendixObject);
	}

	public static java.util.List<reversingunorderedlist.proxies.Orderline> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<reversingunorderedlist.proxies.Orderline> result = new java.util.ArrayList<reversingunorderedlist.proxies.Orderline>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ReversingUnorderedList.Orderline" + xpathConstraint))
			result.add(reversingunorderedlist.proxies.Orderline.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice()
	{
		return getTotalPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalPrice.toString());
	}

	/**
	 * Set value of TotalPrice
	 * @param totalprice
	 */
	public final void setTotalPrice(java.math.BigDecimal totalprice)
	{
		setTotalPrice(getContext(), totalprice);
	}

	/**
	 * Set value of TotalPrice
	 * @param context
	 * @param totalprice
	 */
	public final void setTotalPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalprice)
	{
		getMendixObject().setValue(context, MemberNames.TotalPrice.toString(), totalprice);
	}

	/**
	 * Set value of OrderlineStatus
	 * @param orderlinestatus
	 */
	public final reversingunorderedlist.proxies.OrderlineStatusses getOrderlineStatus()
	{
		return getOrderlineStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderlineStatus
	 */
	public final reversingunorderedlist.proxies.OrderlineStatusses getOrderlineStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OrderlineStatus.toString());
		if (obj == null)
			return null;

		return reversingunorderedlist.proxies.OrderlineStatusses.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OrderlineStatus
	 * @param orderlinestatus
	 */
	public final void setOrderlineStatus(reversingunorderedlist.proxies.OrderlineStatusses orderlinestatus)
	{
		setOrderlineStatus(getContext(), orderlinestatus);
	}

	/**
	 * Set value of OrderlineStatus
	 * @param context
	 * @param orderlinestatus
	 */
	public final void setOrderlineStatus(com.mendix.systemwideinterfaces.core.IContext context, reversingunorderedlist.proxies.OrderlineStatusses orderlinestatus)
	{
		if (orderlinestatus != null)
			getMendixObject().setValue(context, MemberNames.OrderlineStatus.toString(), orderlinestatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.OrderlineStatus.toString(), null);
	}

	/**
	 * @return value of Attribute5
	 */
	public final java.lang.String getAttribute5()
	{
		return getAttribute5(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute5
	 */
	public final java.lang.String getAttribute5(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute5.toString());
	}

	/**
	 * Set value of Attribute5
	 * @param attribute5
	 */
	public final void setAttribute5(java.lang.String attribute5)
	{
		setAttribute5(getContext(), attribute5);
	}

	/**
	 * Set value of Attribute5
	 * @param context
	 * @param attribute5
	 */
	public final void setAttribute5(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute5)
	{
		getMendixObject().setValue(context, MemberNames.Attribute5.toString(), attribute5);
	}

	/**
	 * @return value of Attribute6
	 */
	public final java.lang.String getAttribute6()
	{
		return getAttribute6(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute6
	 */
	public final java.lang.String getAttribute6(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute6.toString());
	}

	/**
	 * Set value of Attribute6
	 * @param attribute6
	 */
	public final void setAttribute6(java.lang.String attribute6)
	{
		setAttribute6(getContext(), attribute6);
	}

	/**
	 * Set value of Attribute6
	 * @param context
	 * @param attribute6
	 */
	public final void setAttribute6(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute6)
	{
		getMendixObject().setValue(context, MemberNames.Attribute6.toString(), attribute6);
	}

	/**
	 * @return value of Attribute7
	 */
	public final java.lang.String getAttribute7()
	{
		return getAttribute7(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute7
	 */
	public final java.lang.String getAttribute7(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute7.toString());
	}

	/**
	 * Set value of Attribute7
	 * @param attribute7
	 */
	public final void setAttribute7(java.lang.String attribute7)
	{
		setAttribute7(getContext(), attribute7);
	}

	/**
	 * Set value of Attribute7
	 * @param context
	 * @param attribute7
	 */
	public final void setAttribute7(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute7)
	{
		getMendixObject().setValue(context, MemberNames.Attribute7.toString(), attribute7);
	}

	/**
	 * @return value of Attribute8
	 */
	public final java.lang.String getAttribute8()
	{
		return getAttribute8(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute8
	 */
	public final java.lang.String getAttribute8(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute8.toString());
	}

	/**
	 * Set value of Attribute8
	 * @param attribute8
	 */
	public final void setAttribute8(java.lang.String attribute8)
	{
		setAttribute8(getContext(), attribute8);
	}

	/**
	 * Set value of Attribute8
	 * @param context
	 * @param attribute8
	 */
	public final void setAttribute8(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute8)
	{
		getMendixObject().setValue(context, MemberNames.Attribute8.toString(), attribute8);
	}

	/**
	 * @return value of Attribute9
	 */
	public final java.lang.String getAttribute9()
	{
		return getAttribute9(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute9
	 */
	public final java.lang.String getAttribute9(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute9.toString());
	}

	/**
	 * Set value of Attribute9
	 * @param attribute9
	 */
	public final void setAttribute9(java.lang.String attribute9)
	{
		setAttribute9(getContext(), attribute9);
	}

	/**
	 * Set value of Attribute9
	 * @param context
	 * @param attribute9
	 */
	public final void setAttribute9(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute9)
	{
		getMendixObject().setValue(context, MemberNames.Attribute9.toString(), attribute9);
	}

	/**
	 * @return value of Orderline_Order
	 */
	public final reversingunorderedlist.proxies.Order getOrderline_Order() throws com.mendix.core.CoreException
	{
		return getOrderline_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of Orderline_Order
	 */
	public final reversingunorderedlist.proxies.Order getOrderline_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		reversingunorderedlist.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Orderline_Order.toString());
		if (identifier != null)
			result = reversingunorderedlist.proxies.Order.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Orderline_Order
	 * @param orderline_order
	 */
	public final void setOrderline_Order(reversingunorderedlist.proxies.Order orderline_order)
	{
		setOrderline_Order(getContext(), orderline_order);
	}

	/**
	 * Set value of Orderline_Order
	 * @param context
	 * @param orderline_order
	 */
	public final void setOrderline_Order(com.mendix.systemwideinterfaces.core.IContext context, reversingunorderedlist.proxies.Order orderline_order)
	{
		if (orderline_order == null)
			getMendixObject().setValue(context, MemberNames.Orderline_Order.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Orderline_Order.toString(), orderline_order.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderlineMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final reversingunorderedlist.proxies.Orderline that = (reversingunorderedlist.proxies.Orderline) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ReversingUnorderedList.Orderline";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
