// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package reversingunorderedlist.proxies;

public enum OrderStatusses
{
	Open(new java.lang.String[][] { new java.lang.String[] { "en_US", "Open" } }),
	In_progress(new java.lang.String[][] { new java.lang.String[] { "en_US", "In progress" } }),
	Delivered(new java.lang.String[][] { new java.lang.String[] { "en_US", "Delivered" } }),
	Ready_and_Closed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Ready and Closed" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private OrderStatusses(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
