// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restdemo.proxies;

public enum Enum_Unit
{
	Container(new java.lang.String[][] { new java.lang.String[] { "en_US", "Container" } }),
	Cubic_meter(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cubic meter" } }),
	Kilo(new java.lang.String[][] { new java.lang.String[] { "en_US", "Kilo" } }),
	Liter(new java.lang.String[][] { new java.lang.String[] { "en_US", "Liter" } }),
	Piece(new java.lang.String[][] { new java.lang.String[] { "en_US", "Piece" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_Unit(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
