// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restdemo.proxies;

public class Orderline
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderlineMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RestDemo.Orderline";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Articlenumber("Articlenumber"),
		Price("Price"),
		Quantity("Quantity"),
		Unit("Unit"),
		Orderline_Order("RestDemo.Orderline_Order");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Orderline(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RestDemo.Orderline"));
	}

	protected Orderline(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderlineMendixObject)
	{
		if (orderlineMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RestDemo.Orderline", orderlineMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RestDemo.Orderline");

		this.orderlineMendixObject = orderlineMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Orderline.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static restdemo.proxies.Orderline initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return restdemo.proxies.Orderline.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static restdemo.proxies.Orderline initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new restdemo.proxies.Orderline(context, mendixObject);
	}

	public static restdemo.proxies.Orderline load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return restdemo.proxies.Orderline.initialize(context, mendixObject);
	}

	public static java.util.List<restdemo.proxies.Orderline> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<restdemo.proxies.Orderline> result = new java.util.ArrayList<restdemo.proxies.Orderline>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RestDemo.Orderline" + xpathConstraint))
			result.add(restdemo.proxies.Orderline.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Articlenumber
	 */
	public final java.lang.String getArticlenumber()
	{
		return getArticlenumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Articlenumber
	 */
	public final java.lang.String getArticlenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Articlenumber.toString());
	}

	/**
	 * Set value of Articlenumber
	 * @param articlenumber
	 */
	public final void setArticlenumber(java.lang.String articlenumber)
	{
		setArticlenumber(getContext(), articlenumber);
	}

	/**
	 * Set value of Articlenumber
	 * @param context
	 * @param articlenumber
	 */
	public final void setArticlenumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String articlenumber)
	{
		getMendixObject().setValue(context, MemberNames.Articlenumber.toString(), articlenumber);
	}

	/**
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(java.math.BigDecimal price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Integer quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * Set value of Unit
	 * @param unit
	 */
	public final restdemo.proxies.Enum_Unit getUnit()
	{
		return getUnit(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit
	 */
	public final restdemo.proxies.Enum_Unit getUnit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Unit.toString());
		if (obj == null)
			return null;

		return restdemo.proxies.Enum_Unit.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Unit
	 * @param unit
	 */
	public final void setUnit(restdemo.proxies.Enum_Unit unit)
	{
		setUnit(getContext(), unit);
	}

	/**
	 * Set value of Unit
	 * @param context
	 * @param unit
	 */
	public final void setUnit(com.mendix.systemwideinterfaces.core.IContext context, restdemo.proxies.Enum_Unit unit)
	{
		if (unit != null)
			getMendixObject().setValue(context, MemberNames.Unit.toString(), unit.toString());
		else
			getMendixObject().setValue(context, MemberNames.Unit.toString(), null);
	}

	/**
	 * @return value of Orderline_Order
	 */
	public final restdemo.proxies.Order getOrderline_Order() throws com.mendix.core.CoreException
	{
		return getOrderline_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of Orderline_Order
	 */
	public final restdemo.proxies.Order getOrderline_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		restdemo.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Orderline_Order.toString());
		if (identifier != null)
			result = restdemo.proxies.Order.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Orderline_Order
	 * @param orderline_order
	 */
	public final void setOrderline_Order(restdemo.proxies.Order orderline_order)
	{
		setOrderline_Order(getContext(), orderline_order);
	}

	/**
	 * Set value of Orderline_Order
	 * @param context
	 * @param orderline_order
	 */
	public final void setOrderline_Order(com.mendix.systemwideinterfaces.core.IContext context, restdemo.proxies.Order orderline_order)
	{
		if (orderline_order == null)
			getMendixObject().setValue(context, MemberNames.Orderline_Order.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Orderline_Order.toString(), orderline_order.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderlineMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final restdemo.proxies.Orderline that = (restdemo.proxies.Orderline) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RestDemo.Orderline";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
